src/Entity/Categories.php
<?php

namespace App\Entity;

use App\Repository\CategoriesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategoriesRepository::class)]
class Categories
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\Length(min:3,minMessage:"il faut min 3 caracteres")]
    #[Assert\NotBlank(message: "champ obligatoire")]
    private ?string $Nom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }
}

src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as assert;

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce Champ est Obligatoire")]
    #[Assert\Length(min:4,max:30,minMessage:"il faut un Minimum de 4 lettres et maximum 30 lettres")]
    #[Assert\Regex(pattern:"/^[a-zA-Z\s]+$/")]
    private ?string $objet = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"Ce Champ est Obligatoire")]
    #[Assert\Length(min:10,minMessage:"il faut un Minimum de 10 lettres")]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE , nullable : true)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(length: 255, nullable : true)]
    private ?string $etat = null;

    #[ORM\ManyToOne]
    private ?User $user = null;

   
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getObjet(): ?string
    {
        return $this->objet;
    }

    public function setObjet(string $objet): self
    {
        $this->objet = $objet;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    

    
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;


class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('objet')
            ->add('description')
            ->add('type', ChoiceType::class, [
                'choices'  => [
                   'Medecin' => 'Medecin',
                   'Produit' => 'Produit ',
                   'Pharmacie' => 'Pharmacie ',
            ],
            ])
            ->add('submit',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Repository\ReclamationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Reclamation;
use App\Form\ReclamationType;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\UserRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Snappy\Pdf;

class ReclamationController extends AbstractController
{
#[Route('/reclamation_ajout', name: 'reclamation_ajout')]
    public function ajout_reclamation(Request $request,UserRepository $rp): Response
    {
        $user=$rp->find(7);
        $reclamation=new Reclamation();
        $form=$this->createForm(ReclamationType::class,$reclamation);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $em=$this->getDoctrine()->getManager();
            $reclamation->setEtat("en attente");
            $reclamation->setUser($user);
            $reclamation->setDate(new \DateTime("now"));
            $em->persist($reclamation);
            $em->flush();
            return $this->redirectToRoute("afficher_reclamation");

        }

      
        return $this->render('reclamation/ajout_reclamation.html.twig', [
            'f' => $form->createView(),
        ]);
       
    }
    

    #[Route('/afficher_reclamation', name: 'afficher_reclamation')]
    public function afficher_reclamation(ReclamationRepository $repository): Response
    {

        
        $reclamation=$repository->findAll();
     
        return $this->render('reclamation/afficher_reclamation.html.twig',[
            'rec' => $reclamation,
            
         
        ] );
    }
    #[Route('reclamation/remove/{id}', name: 'remover')]
    public function removeback(ManagerRegistry $doctrine,$id): Response
    {
        $em= $doctrine->getManager();
        $Reclamation= $doctrine->getRepository(Reclamation::class)->find($id);
        $em->remove($Reclamation);
        $em->flush();
        return $this->redirectToRoute('afficher_reclamation');
    }
    
    
    #[Route('/f/afficher_reclamation2', name: 'afficher_reclamation_user')]
    public function afficher_reclamation_user(ReclamationRepository $repository,UserRepository $urp): Response
    {

        $user=$urp->find(7);
        $reclamation=$repository->findByuser($user);
     
        return $this->render('reclamation/afficher2_reclamation.html.twig',[
            'rec' => $reclamation,
            
         
        ] );
    }
    #[Route('/f/afficher_reclamation/nontraité', name: 'afficher_reclamation_user_nontraité')]
    public function afficher_reclamation_user_nontraité(ReclamationRepository $repository,UserRepository $urp): Response
    {
        $rec=$repository->findAll();
        $recs=$repository->findbynontraite("en attente");
        return $this->render('reclamation/nontraité.html.twig',[
            'rec' => $rec,
            'recs'=>$recs
            
         
        ] );

    }
    #[Route('/f/afficher_reclamation/traité', name: 'afficher_reclamation_user_traité')]
    public function afficher_reclamation_user_traité(ReclamationRepository $repository,UserRepository $urp): Response
    {
        $rec=$repository->findAll();
        $recs=$repository->findbynontraite("traite");
        return $this->render('reclamation/traité.html.twig',[
            'rec' => $rec,
            'recs'=>$recs
            
         
        ] );

    }



    /**
     * @Route ("/Imprimer/{id}" ,name="imp")
     */

     public function pdf($id,ReclamationRepository $repository)
     {
         // Configure Dompdf according to your needs
         $pdfOptions = new Options();
         $pdfOptions->set('defaultFont', 'Arial');
 
         // Instantiate Dompdf with our options
         $dompdf = new Dompdf($pdfOptions);
         $reclamation=$repository->find($id);
 
         $html = $this->renderView('reclamation/imp_pdf.html.twig',
             ['reclamation' => $reclamation
             ]);
         // Load HTML to Dompdf
         $dompdf->loadHtml($html);
 
         // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
         $dompdf->setPaper('A4', 'portrait');
 
 
         // Render the HTML as PDF
         $dompdf->render();
         $pdfFilePath = 'C:/Users/hp/Downloads/aziiz.pdf';
         file_put_contents($pdfFilePath, $dompdf->output());
         $response = new Response(file_get_contents($pdfFilePath));
         $response->headers->set('Content-Type', 'application/pdf');
         $response->headers->set('Content-Disposition', 'attachment; filename="document.pdf"');
         return $response;
            }
 
}

templates/reclamation/afficher2_reclamation.html.twig
{% extends 'base.html.twig' %}


{% block title %}Liste des Reclamation{% endblock %}
{% block body %}



    <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area gradient-bg bg-cover shadow dark text-light text-center" style="background-image: url(assets/img/banner/8.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>Nous contacter</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i>Acceuil</a></li>
                        <li><a href="#">NOS</a></li>
                        <li class="active">Contacts</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->
    <!-- Star Feature Entry Area
    ============================================= -->
    <div class="feature-entry-area default-padding-bottom">
        <!-- Shape -->
        <div class="shape">
            <img src="assets/img/shape/1.png" alt="Shape">
        </div>
        <!-- End Shape -->
      
        <div class="item ">
            <div class="feature-entry-items text-center">
                <div class="row">
                    <!-- Single Item -->
                      {% for r in rec %}
                    <div class="col-lg-3 single-item">
                        <div class="item">
                            <i class="flaticon-ambulance-1"></i>
                            <h4>{{r.objet}}</h4>
                            <p>
                              {{r.description}}
                            </p>

                            
                           
                        </div>
                         <a class="btn btn-md btn-gradient circle"  href="{{ path ('afficherrep',{'id':r.id}) }}">Afficher Reponse <i class="fas fa-angle-right"></i></a>
                    <a class="btn btn-md btn-gradient circle"  href="{{ path ('imp',{'id':r.id}) }}">Imprimer <i class="fas fa-angle-right"></i></a>

                    </div>
                   
                    {% endfor %}
                    <!-- End Single Item -->
                    <!-- Single Item -->
                 
                    
                </div>
            </div>
        </div>
    </div>
    
   {% endblock %}
    
   

templates/reclamation/afficher_reclamation.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Liste des Reclamation{% endblock %}

{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>Liste des Reclamations</h2>
                    <ul class="breadcrumb padding-0">
                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Reclamations</a></li>
                        <li class="breadcrumb-item active">Liste des Reclamations</li>
                    </ul>
                </div>            
               
            </div>
        </div>
        <!-- Basic Examples -->
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2> Liste des <strong>Reclamations</strong> </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu slideUp">
                                    <li><a href="javascript:void(0);">Action</a></li>
                                    <li><a href="javascript:void(0);">Another action</a></li>
                                    <li><a href="javascript:void(0);">Something else</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                                <thead>
                                    <tr>
                                        <th>Nom et Prenom </th>
                                        <th>Objet </th>
                                        <th>Type</th>
                                        <th>Description</th>
                                        <th>Date</th>
                                        <th>Etat</th>
                                        <th></th>
                                        <th></th>
                                        
                                    </tr>
                                </thead>
                               
                                <tbody>
                                {% for a in rec %}
                                  
                                    <tr>
                                    {% if a.user != null %}
                                        <td>{{a.user.nom}} {{a.user.prenom}}</td>
                                        {% else %}
                                        <td>hata iji el user</td>
                                        {% endif %}
                                        <td>{{a.objet}}</td>
                                        <td>{{a.type}}</td>
                                        <td>{{a.description}}</td>
                                        <td>{{a.date|date("d/m/Y")}}</td>
                                        <td>{{a.etat}}</td>

                                        
                                        
                                
                                        
                                        <td><a class="button button-small edit" title="Delete" href="{{ path ('remover',{'id':a.id}) }}"><i class="zmdi zmdi-delete"></i>   Supprimer</a></td>
                                        <td><a class="button button-small edit"  href="{{ path ('reponseajout',{'id':a.id}) }}"><i class="zmdi zmdi-delete"></i>   traiter</a></td>
                                    </tr>
                                  
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Basic Examples --> 
        
        <!-- #END# Exportable Table --> 
    </div>
</section>
{% endblock %}

templates/reclamation/ajout_reclamation.html.twig
{% extends 'base.html.twig' %}

{% block title %}ajouter une reclamation
{% endblock %}



{% block body %}
 <!-- Start Breadcrumb 
    ============================================= -->
    <div class="breadcrumb-area gradient-bg bg-cover shadow dark text-light text-center" style="background-image: url(front/img/banner/8.jpg);">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 offset-lg-2">
                    <h1>Nous contacter</h1>
                    <ul class="breadcrumb">
                        <li><a href="#"><i class="fas fa-home"></i>Acceuil</a></li>
                        <li><a href="#">NOS</a></li>
                        <li class="active">Contacts</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumb -->

    <!-- Start Contact Area
    ============================================= -->
    <div class="contact-area default-padding">
        <div class="container">
            <div class="contact-items">
                <div class="row">
                    
                    <div class="col-lg-8 left-item">
                        <div class="content">
                            <h2>Contact our <strong>Support Office</strong></h2>
							{{ form_start(f,  {'attr': {'novalidate':'novalidate'}}) }}
                            
                                
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
										{{ form_widget(f.objet,  {'attr': { 'class':'form-control', 'placeholder': 'Objet'}}) }}
                                                <span class="text-danger">{{ form_errors(f.objet,{'attr':{'class':'text-danger'}})}}</span>

                                            <span class="alert-error"></span>

                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
										{{ form_widget(f.type,  {'attr': { 'class':'form-control'}}) }}
                                            
                                            <span class="alert-error"></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="form-group comments">
								{{ form_widget(f.description,  {'attr': { 'class':'form-control', 'placeholder': 'description'}}) }}
								<span class="text-danger">{{ form_errors(f.description,{'attr':{'class':'text-danger'}})}}</span>
                                   
								   
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
										{{ form_widget(f.submit,  {'attr': { 'class':''}}) }}

                                        
                                    </div>
                                </div>
                                
                            {{ form_end(f) }}
                        </div>
                    </div>

                   

                </div>
            </div>
        </div>
    </div>
    <!-- End Contact -->

{% endblock %}


	


				

templates/reclamation/imp_pdf.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Example 1</title>
    <link rel="stylesheet" href="/style.css" media="all" />
</head>
<body>
<header class="clearfix">
    <div id="logo">
        DoCare
    </div>
    <h1 align="center">Reclamation DoCare </h1>
    <hr></hr>
    <hr></hr>
    <div id="company" class="clearfix">
        <div><span>Objet </span> {{ reclamation.objet }} </div>
        <div><span>description</span> {{ reclamation.description}}  </div>
        <div class="alert-danger"><span class="alert-danger">date</span> {{ reclamation.date |date("d/m/Y") }} </div>



    </div><hr></hr>
    <div id="project">
        <div><span>type</span> {{ reclamation.type }}</div>
        <div><span>etat</span> {{ reclamation.etat }} </div>
    </div>
</header>

<hr></hr>

<div id="notices">
    <div>NOTICE:</div>
    <div class="notice">l'equipe DOCARE vous propose de bon plan</div>
</div>
</main>

</body>

templates/reclamation/nontraité.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Liste des Reclamation{% endblock %}

{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>Liste des Reclamations</h2>
                    <ul class="breadcrumb padding-0">
                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Reclamations</a></li>
                        <li class="breadcrumb-item active">Liste des Reclamations</li>
                    </ul>
                </div>            
               
            </div>
        </div>
        <!-- Basic Examples -->
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2> Liste des <strong>Reclamations</strong> </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu slideUp">
                                    <li><a href="{{path('afficher_reclamation')}}">show all </a></li>
                                    <li><a href="{{path('afficher_reclamation_user_traité')}}">filtrer par traité</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Nom et Prenom </th>
                                        <th>Objet </th>
                                        <th>Type</th>
                                        <th>Description</th>
                                        <th>Date</th>
                                        <th>Etat</th>
                                        <th></th>
                                        <th></th>
                                        
                                    </tr>
                                </thead>
                               
                                <tbody>
                                {% for a in recs %}
                                  
                                    <tr>
                                    {% if a.user != null %}
                                        <td>{{a.user.nom}} {{a.user.prenom}}</td>
                                        {% else %}
                                        <td>hata iji el user</td>
                                        {% endif %}
                                        <td>{{a.objet}}</td>
                                        <td>{{a.type}}</td>
                                        <td>{{a.description}}</td>
                                        <td>{{a.date|date("d/m/Y")}}</td>
                                        <td>{{a.etat}}</td>

                                        
                                        
                                
                                        
                                        <td><a class="button button-small edit" title="Delete" href="{{ path ('remover',{'id':a.id}) }}"><i class="zmdi zmdi-delete"></i>   Supprimer</a></td>
                                        {% if a.etat == "en attente" %}
                                        <td><a class="button button-small edit"  href="{{ path ('reponseajout',{'id':a.id}) }}"><i class="zmdi zmdi-delete"></i>   traiter</a></td>
                                        {% endif %}
                                    </tr>
                                  
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Basic Examples --> 
        
        <!-- #END# Exportable Table --> 
    </div>
</section>
{% endblock %}

templates/reclamation/traité.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Liste des Reclamation{% endblock %}

{% block body %}
<section class="content">
    <div class="container-fluid">
        <div class="block-header">
            <div class="row clearfix">
                <div class="col-lg-5 col-md-5 col-sm-12">
                    <h2>Liste des Reclamations</h2>
                    <ul class="breadcrumb padding-0">
                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i></a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Reclamations</a></li>
                        <li class="breadcrumb-item active">Liste des Reclamations</li>
                    </ul>
                </div>            
               
            </div>
        </div>
        <!-- Basic Examples -->
        <div class="row clearfix">
            <div class="col-lg-12">
                <div class="card">
                    <div class="header">
                        <h2> Liste des <strong>Reclamations</strong> </h2>
                        <ul class="header-dropdown">
                            <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                                <ul class="dropdown-menu slideUp">
                                    <li><a href="{{path('afficher_reclamation')}}">show all </a></li>
                                    <li><a href="{{path('afficher_reclamation_user_nontraité')}}">filtrer par non traité</a></li>
                                </ul>
                            </li>
                            <li class="remove">
                                <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Nom et Prenom </th>
                                        <th>Objet </th>
                                        <th>Type</th>
                                        <th>Description</th>
                                        <th>Date</th>
                                        <th>Etat</th>
                                        <th></th>
                                        <th></th>
                                        
                                    </tr>
                                </thead>
                               
                                <tbody>
                                {% for a in recs %}
                                  
                                    <tr>
                                    {% if a.user != null %}
                                        <td>{{a.user.nom}} {{a.user.prenom}}</td>
                                        {% else %}
                                        <td>hata iji el user</td>
                                        {% endif %}
                                        <td>{{a.objet}}</td>
                                        <td>{{a.type}}</td>
                                        <td>{{a.description}}</td>
                                        <td>{{a.date|date("d/m/Y")}}</td>
                                        <td>{{a.etat}}</td>

                                        
                                        
                                
                                        
                                        <td><a class="button button-small edit" title="Delete" href="{{ path ('remover',{'id':a.id}) }}"><i class="zmdi zmdi-delete"></i>   Supprimer</a></td>
                                        {% if a.etat == "en attente" %}
                                        <td><a class="button button-small edit"  href="{{ path ('reponseajout',{'id':a.id}) }}"><i class="zmdi zmdi-delete"></i>   traiter</a></td>
                                        {% endif %}
                                    </tr>
                                  
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Basic Examples --> 
        
        <!-- #END# Exportable Table --> 
    </div>
</section>
{% endblock %}